# Generated by Django 5.1.7 on 2025-04-30 13:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('another_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, max_length=800, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='myPersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=80, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('facebook', models.CharField(blank=True, max_length=100, null=True)),
                ('instagram', models.CharField(blank=True, max_length=100, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=100, null=True)),
                ('github', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('another_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, max_length=800, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('skills', models.CharField(blank=True, max_length=800, null=True)),
                ('education', models.TextField(blank=True, max_length=800, null=True)),
                ('job', models.CharField(blank=True, max_length=200, null=True)),
                ('hits', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True, max_length=800, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/portfolio/')),
                ('link', models.CharField(blank=True, max_length=100, null=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
