# Generated by Django 5.1.7 on 2025-03-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('another_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(max_length=800)),
            ],
        ),
    ]
