# Generated by Django 5.1.7 on 2025-03-28 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='myPersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('facebook', models.EmailField(blank=True, max_length=100, null=True)),
                ('instagram', models.EmailField(blank=True, max_length=100, null=True)),
                ('linkedin', models.EmailField(blank=True, max_length=100, null=True)),
                ('github', models.EmailField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('another_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, max_length=800, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='description',
            field=models.TextField(blank=True, max_length=800, null=True),
        ),
    ]
