# Generated by Django 5.1.7 on 2025-03-28 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_mypersonalinfo_alter_contact_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='mypersonalinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mypersonalinfo',
            name='facebook',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mypersonalinfo',
            name='github',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mypersonalinfo',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mypersonalinfo',
            name='linkedin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
