# Generated by Django 5.1.7 on 2025-03-28 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_mypersonalinfo_email_alter_mypersonalinfo_facebook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mypersonalinfo',
            name='education',
            field=models.TextField(blank=True, max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='mypersonalinfo',
            name='skills',
            field=models.TextField(blank=True, max_length=800, null=True),
        ),
    ]
