# Generated by Django 5.1.7 on 2025-03-29 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_portfolio_mypersonalinfo_education_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mypersonalinfo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='upload/images/personal/'),
        ),
        migrations.AlterField(
            model_name='mypersonalinfo',
            name='name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='upload/images/portfolio/'),
        ),
    ]
