# Generated by Django 5.1.7 on 2025-03-30 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_mypersonalinfo_image_alter_mypersonalinfo_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mypersonalinfo',
            name='hits',
            field=models.IntegerField(default=0),
        ),
    ]
