# Generated by Django 5.1.7 on 2025-03-31 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_mypersonalinfo_hits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mypersonalinfo',
            name='image',
            field=models.ImageField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
