# Generated by Django 5.1.7 on 2025-03-31 23:17

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_mypersonalinfo_image_alter_portfolio_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mypersonalinfo',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image/portfolio'),
        ),
    ]
